/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#006763",
        "primary-container": "#00837e",
        "on-primary": "#ffffff",
        "on-primary-container": "#f3fffd",
        "primary-fixed": "#7ef6ee",
        "primary-fixed-dim": "#5fd9d2",
        "inverse-primary": "#5fd9d2",
        "secondary": "#5d5f5f",
        "secondary-container": "#dfe0e0",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#616363",
        "secondary-fixed": "#e2e2e2",
        "secondary-fixed-dim": "#c6c6c7",
        "tertiary": "#93461e",
        "tertiary-container": "#b25e34",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#ffdbcc",
        "tertiary-fixed-dim": "#ffb695",
        "surface": "#f5faf9",
        "surface-dim": "#d5dbda",
        "surface-bright": "#f5faf9",
        "surface-container": "#e9efed",
        "surface-container-low": "#eff5f3",
        "surface-container-high": "#e4e9e8",
        "surface-container-highest": "#dee4e2",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#dee4e2",
        "surface-tint": "#006a66",
        "on-surface": "#171d1c",
        "on-surface-variant": "#3d4948",
        "on-background": "#171d1c",
        "background": "#f5faf9",
        "outline": "#6d7a78",
        "outline-variant": "#bcc9c7",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#2c3231",
        "inverse-on-surface": "#ecf2f0",
        "ice-latte": "#E4DDD3",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "unit": "8px",
        "stack-sm": "12px",
        "gutter": "16px",
        "stack-md": "24px",
        "container-padding": "24px",
        "stack-lg": "40px",
      },
      fontFamily: {
        "grotesk": ["Space Grotesk", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
      },
      fontSize: {
        "caption": ["12px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "action": ["16px", { lineHeight: "1.0", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "h2": ["28px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h1": ["40px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "float": "float 6s ease-in-out infinite",
        "status-pulse": "statusPulse 2s infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        statusPulse: {
          "0%": { boxShadow: "0 0 0 0 rgba(0, 161, 155, 0.7)" },
          "70%": { boxShadow: "0 0 0 8px rgba(0, 161, 155, 0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(0, 161, 155, 0)" },
        },
      },
    },
  },
  plugins: [],
};
